### ISSUE TITLE
Set issue labels

### ISSUE THREAD

**Issue by korikuzma** [GenomicMedLab/wagner-lab-issues#12]
Specifically, it might be good to find issues in our repos that could have a `good first issue` label for new people.

**Comment by jsstevenson** [comment]
+ are there other issue custom labels we like? and can we get in the habit of labeling issues as they're created?

**Comment by korikuzma** [comment]
@jsstevenson 
I do think we should add other kinds of labels. I've added some refactoring ones in a different repo. 
I also think we should get in the habit of always labeling issues.

**Comment by jsstevenson** [comment]
I've been using "backend" and either "frontend" or "UI/UX" for full stack projects, and stuff like "requirement" for MVP-esque issues (that might be better met by assigning those issues to epics though)

**Comment by korikuzma** [comment]
https://github.com/ManageIQ/guides/blob/master/labels.md

**Comment by korikuzma** [comment]
@jsstevenson @katiestahl  @mcannon068nw  @wesleygoar  @jarbesfeld Added to our lab knowledgebase [here](https://github.com/GenomicMedLab/lab-knowledgebase/blob/main/misc/github_labels.md). Let me know if you think we should add / remove / edit any.

**Comment by korikuzma** [comment]
@jsstevenson @katiestahl @mcannon068nw @wesleygoar @jarbesfeld Made some additional changes. Let me know if [this](https://github.com/GenomicMedLab/lab-knowledgebase/blob/main/misc/github_labels.md) version is good.

**Comment by jsstevenson** [comment]
@korikuzma if a user posts an issue relating to installation challenges, would that be tagged as "bug"?

**Comment by korikuzma** [comment]
@jsstevenson If it's them not sure how to follow our installation steps, it would be question / documentation. If they're getting errors during our installation process, then it would be bug imo

**Comment by korikuzma** [comment]
@jsstevenson are you good with the changes? I've updated some of the repos (gene/variation/cool-seq-tool/metakb/varcat) with the labels. If you're good, then I think we can close this issue and update the other repos with the labels. I sent to @katiestahl over slack last Friday and she suggested the change for merging technical debt + refactor.

**Comment by jsstevenson** [comment]
👍  yeah looks good to me
