### ISSUE TITLE
Rebrand VAI to VarCat

### ISSUE THREAD

**Issue by korikuzma** [GenomicMedLab/wagner-lab-issues#13]
![image](https://user-images.githubusercontent.com/42851808/203354672-23745ca5-d06f-4ddf-a2cd-35670b44abfa.png)

**Comment by korikuzma** [comment]
I want to see if @wesleygoar can generate some cool logos from his AI tool that we could potentially use

**Comment by mcannon068nw** [comment]
vector file for VarCat made! where should this live? @korikuzma

**Comment by mcannon068nw** [comment]
Transparent Logo w/ tail:
![varcat-logo-transparent](https://user-images.githubusercontent.com/87494086/208743733-d1555baf-25cf-41c9-9d5c-ebb7ddce4029.png)

Have vectorized images for these, have them locally just let me know if there is an s3 bucket or something I can stash them.

**Comment by jsstevenson** [comment]
@mcannon068nw my pitch would be to:

1) produce files for
    a) just the cat
    b) just the cat's head (could be a good minimized menu logo)
    and add them to the VAI repo
2) having the text is good too (eg for a header image at the top of a repo, or for a slide deck) but isn't something we /need/ in svg (on the site itself we would mostly just render the text via html)

**Comment by wesleygoar** [comment]
I agree with these comments

**Comment by mcannon068nw** [comment]
made the changes and uploaded the svgs to the s3

![varcat-head](https://user-images.githubusercontent.com/87494086/210424336-a724741f-7e15-4892-9ab0-3d71d2b8fad7.svg)
![varcat](https://user-images.githubusercontent.com/87494086/210424338-c59c5ec8-ab07-44aa-904d-9d8b5d229806.svg)

**Comment by korikuzma** [comment]
Thanks @mcannon068nw . I made a separate issue in the VarCat repo. Will close this issue.
