### ISSUE TITLE
Spin up internal metakb instance

### ISSUE THREAD

**Issue by korikuzma** [GenomicMedLab/wagner-lab-issues#15]
- [ ] ec2 for neo4j which contains all sources (civic, moa, oncokb)
- [ ] Only allow access via on prem or VPN (or we can just do IAM roles) 
- [ ] REST APIGW
- [ ] Use the genomicmedlab domain
- [ ] See if we're still able to use the same code pipeline off of metakb branch triggers or if we will have to make a separate pipeline

**Comment by korikuzma** [comment]
If Elastic Beanstalk URL can't be private: WAF, Check IP address if it's NCH, Cognito, or LDAP
EC2 for neo4j: Can we limit permissions on who can query oncokb data? Then we'd be able to possibly use the same db and not have to spin up another instance 
https://neo4j.com/docs/operations-manual/current/authentication-authorization/access-control/#auth-access-control-security

**Comment by korikuzma** [comment]
@ahwagner said we can go the easier route of having a separate private instance just for us. We can revisit this later if costs become an issue

**Comment by korikuzma** [comment]
See if we can have this on the VarCat billing since it will be using this . Send email to Adam + Alex

**Comment by korikuzma** [comment]
> See if we can have this on the VarCat billing since it will be using this . Send email to Adam + Alex

Didn't send an email, just slacked Adam. He will talk to Grant about it.

**Comment by korikuzma** [comment]
Naming: 
- MetaKB internal is the private instance. There will be associated resources with the `internal` word to indicate that it is private
- Due to character limits, the ec2 for the neo4j db will end in `01` for the public and `02` for internal

**Comment by korikuzma** [comment]
- [ ] Set `ELBScheme` to `internal`
![Screen Shot 2023-01-04 at 9 08 51 AM](https://user-images.githubusercontent.com/42851808/210572927-eeef8bf7-4d7f-44c4-9133-f0a8f62823eb.png)

**Comment by wesleygoar** [comment]
@korikuzma what are your current thoughts on this issue? I'm not sure this is necessary for MVP with the way we chose to handle the ingest of the cdm files.

**Comment by korikuzma** [comment]
Not needed.
