### ISSUE TITLE
Fix My Zoom Installation

### ISSUE THREAD

**Issue by mcannon068nw** [GenomicMedLab/wagner-lab-issues#18]
🤷‍♂️ 🤷‍♂️
Matt's Zoom app never wants to work properly, thus Matt only uses browser Zoom. This is not convenient, fix!

**Comment by mcannon068nw** [comment]
fixed by https://community.zoom.com/t5/Meetings/zoom-does-not-connect-to-internet-in-Mac/m-p/1927

**Comment by mcannon068nw** [comment]
Proof:
![Screen Shot 2022-12-20 at 10 29 23 AM](https://user-images.githubusercontent.com/87494086/208704068-70ba8d31-e3aa-4ad6-afaf-7366ae48840c.png)
![Screen Shot 2022-12-20 at 10 31 58 AM (2)](https://user-images.githubusercontent.com/87494086/208704649-0c31642c-e386-45b0-85b0-dded7ba36ca9.png)

**Comment by jsstevenson** [comment]
🥇 🥇 🥇
