### ISSUE TITLE
VarCat Grant

### ISSUE THREAD

**Issue by wesleygoar** [GenomicMedLab/wagner-lab-issues#25]
R21 Prototyping grant for VarCat development. 
https://grants.nih.gov/grants/guide/rfa-files/RFA-CA-24-016.html
"The purpose of this Notice of Funding Opportunity (NOFO) is to invite exploratory/developmental research grant applications (R21) for innovative informatics methods and algorithms to improve the acquisition, analysis, visualization, or interpretation of data across the cancer research continuum including cancer biology, cancer treatment and diagnosis, early cancer detection, risk assessment and prevention, cancer control and epidemiology, and/or cancer health disparities. As a component of the NCI's Informatics Technology for Cancer Research (ITCR) Program, the emphasis of this NOFO is on supporting the development of novel informatics capabilities that involve a high degree of innovation that have the potential to accelerate or enhance research. To be successful, there must be a clear rationale for how the proposed informatics method or algorithm is novel and how it will benefit the cancer research field. Projects with a significant level of data generation and/or data analysis will not be considered responsive to this funding opportunity."

**DUE DATE is June 11th**

**Comment by jsstevenson** [comment]
Whoa
