### ISSUE TITLE
make Lab Presentation Bot™

### ISSUE THREAD

**Issue by jsstevenson** [GenomicMedLab/wagner-lab-issues#27]
* Ingest structured lab presentation schedule
* Send email? (using SES)? to remind presenter of upcoming scheduled presentation

**Comment by korikuzma** [comment]
I'm working on a GH action to create an issue tagging the person to remind them.

**Comment by korikuzma** [comment]
Forgot to update. We're trialing this out in https://github.com/GenomicMedLab/lab-presentations . 

> For presentations scheduled two weeks out, a reminder will be sent through a GitHub issue assigned to you. Additionally, you will receive a follow-up reminder one week prior via a comment on the issue. Please close the issue once completed.

I created a slack channel that I'm trialing out with @katiestahl and @mcannon068nw . The slack channel tracks the GH repo so people will get GH/email notification as well as a slack notification. Will add others to the channel next week.

**Comment by korikuzma** [comment]
This seems to be working, so will close this. We can re-open if we would like to change the approach.
