### ISSUE TITLE
Festive name for the week of December 19th-23rd

### ISSUE THREAD

**Issue by ahwagner** [GenomicMedLab/wagner-lab-issues#7]
For the week of December 19th-23rd, I want us to put research projects on hold and focus on projects that facilitate lab efficiency, teamwork, and/or training. I am looking for project ideas that improve communication, education, outreach, workflows, etc. within our team, IGM, or the broader research community. This can include, but is not limited to, Wagner Lab internally- and externally-facing sites, project documentation, getting started guides, best practices manuscripts, coding style guides / linters, etc.

I would like a festive name for this week–please put ideas on what to call it in this thread.

**Comment by korikuzma** [comment]
Tech the halls ❄️ 💻

**Comment by mcannon068nw** [comment]
ELF on A SHELF
**E**xceptional **L**ab **F**ocus on **A**ll **S**hared **H**andbook, **E**ducational **L**earning **F**acilities
