### ISSUE TITLE
Lab software standards, software project templates

### ISSUE THREAD

**Issue by jsstevenson** [GenomicMedLab/wagner-lab-issues#8]
This is highly aspirational, but I'd be interested in defining some common code and project standards where possible. All of this would be domain and/or language specific, but I'm thinking of stuff like (taking Python as an example)

- Linting/formatting (Black? Flake8? And any custom settings therein. Plus Isort, Darglint)
- Testing (We're more or less settled on Pytest, but what kind of coverage tools and settings? Use Tox for encapsulated testing? Run mypy checks as well?)
- Common pre-commit hooks for as much of the above as possible
- Build tool -- pyproject.toml?
- Environment management - stick with Pipenv or move to Poetry?
- CI driven checks on conventional commit messages? Auto generate release notes and versioning?

In particular, if we could identify consistent elements from the above that could structure a [Cookie Cutter](https://cookiecutter.readthedocs.io/en/stable/) template, that might be useful for ensuring that new projects start on the right foot, and with minimal labor to tack on necessary boilerplate.

**Comment by jsstevenson** [comment]
Relevant: https://github.com/cancervariants/variation-normalization/issues/475

**Comment by korikuzma** [comment]
@jsstevenson You did it! https://github.com/GenomicMedLab/software-templates 🚀 . I'm going to close this issue
