### ISSUE TITLE
Lab Handbook

### ISSUE THREAD

**Issue by korikuzma** [GenomicMedLab/wagner-lab-issues#9]
https://docs.google.com/document/d/1_WnB1QmzcV2ITUiy0SqW7Epzc-g9xtOZL0bfWqE_kWE/edit?usp=sharing

**Comment by korikuzma** [comment]
@jsstevenson do you think we should have two separate handbooks? One for general lab + another for developers?

**Comment by jsstevenson** [comment]
I think we should focus on things that are pretty general, and we could designate certain items as skippable to certain people? But things like issue tracking, dev environment setup, and prerequisite knowledge are probably true for every kind of lab member

**Comment by korikuzma** [comment]
Main components are finished. Will continue to update as needed.
